### ISSUE TITLE
Requirements for the environment

### ISSUE THREAD

**Issue by ShaniaShan** [HanxunH/CognitiveDistillation#2]
Thanks for sharing your wonderful work. When I tried to run the code, it threw errors due to dependency conflicts of packages' versions: omegaconf, fairseq, hydra-core, and mlconfig. Could you please provide the requirements.txt for setting up the environment?  Thanks.

**Comment by HanxunH** [comment]
Hi,

Thanks for your interest in our work. 

If you are interested in using the Cognitive Distillation, it can be used as a standalone tool (with PyTorch as a dependency). https://github.com/HanxunH/CognitiveDistillation/blob/main/detection/cognitive_distillation.py

If you are interested in reproducing the results from the paper, `mlconfig==0.1.0` is needed along with other packages stated here: https://github.com/HanxunH/CognitiveDistillation/blob/main/requirements.txt


> Thanks for sharing your wonderful work. When I tried to run the code, it threw errors due to dependency conflicts of packages' versions: omegaconf, fairseq, hydra-core, and mlconfig. Could you please provide the requirements.txt for setting up the environment? Thanks.

I'm not sure where the conflict came from. I did not use any except for the `mlconfig`, but if it is the `mlconfig`, feel free to remove it and use hard code or `argparse` to configure the experiments.

**Comment by ShaniaShan** [comment]
> Thanks for sharing your wonderful work. When I tried to run the code, it threw errors due to dependency conflicts of packages' versions: omegaconf, fairseq, hydra-core, and mlconfig. Could you please provide the requirements.txt for setting up the environment? Thanks.
